name: Feature Request
description: Ask for a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        We're always looking to improve our packages. If you have a feature request, please let us know.
